name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  NODE_VER: 22

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js v${{env.NODE_VER}}
        uses: actions/setup-node@v5
        with:
          node-version: ${{env.NODE_VER}}
          cache: pnpm

      - name: Install dependencies
        run: pnpm -r install

      - name: Stub
        run: pnpm stub

      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js v${{env.NODE_VER}}
        uses: actions/setup-node@v5
        with:
          node-version: ${{env.NODE_VER}}
          cache: pnpm

      - name: Install dependencies
        run: pnpm -r install

      - name: Stub
        run: pnpm stub

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
