name: Publish NPM Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  NODE_VER: 22

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js v${{env.NODE_VER}}
        uses: actions/setup-node@v5
        with:
          node-version: ${{env.NODE_VER}}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm -r install

      - name: Build packages
        run: pnpm run build

      - name: Publish `@windi-ui/core` to NPM registry
        run: cd packages/windui-core && pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true

      - name: Publish `@windi-ui/tailwind` to NPM registry
        run: cd packages/windui-tailwind && pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true

      - name: Generate changelog and release on GitHub
        run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
